-------------------------------------------------------IMDB MOVIE ANALYSIS------------------------------------------------------------------------------

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"D:\Ind\projects\Career fair project\IMDB_Movies.csv")

In [3]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [4]:
df.shape

(5043, 28)

In [5]:
df.dropna(inplace=True)

In [6]:
df.isnull().sum()

color                        0
director_name                0
num_critic_for_reviews       0
duration                     0
director_facebook_likes      0
actor_3_facebook_likes       0
actor_2_name                 0
actor_1_facebook_likes       0
gross                        0
genres                       0
actor_1_name                 0
movie_title                  0
num_voted_users              0
cast_total_facebook_likes    0
actor_3_name                 0
facenumber_in_poster         0
plot_keywords                0
movie_imdb_link              0
num_user_for_reviews         0
language                     0
country                      0
content_rating               0
budget                       0
title_year                   0
actor_2_facebook_likes       0
imdb_score                   0
aspect_ratio                 0
movie_facebook_likes         0
dtype: int64

In [7]:
df['num_critic_for_reviews']=df['num_critic_for_reviews'].astype(int)
df['duration']=df['duration'].astype(int)
df['director_facebook_likes']=df['director_facebook_likes'].astype(int)
df['actor_3_facebook_likes']=df['actor_3_facebook_likes'].astype(int)
df['actor_1_facebook_likes']=df['actor_1_facebook_likes'].astype(int)
df['gross']=df['gross'].astype(int)
df['budget']=df['budget'].astype(int)
df['title_year']=df['title_year'].astype(int)
df['actor_2_facebook_likes']=df['actor_2_facebook_likes'].astype(int)
df['movie_facebook_likes']=df['movie_facebook_likes'].astype(int)

In [8]:
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,3755.000000,3755.000000,3755.000000,3755.000000,3755.000000,3.755000e+03,3.755000e+03,3755.000000,3755.000000,3.755000e+03,3755.000000,3755.000000,3755.000000,3755.000000,3755.000000
mean,167.392277,110.260186,807.463648,771.484953,7753.390146,5.262614e+07,1.058489e+05,11530.158988,1.377630,3.828393e+07,2002.974434,2022.314248,6.464740,2.110951,9349.396272
std,123.465521,22.649332,3068.570417,1894.460316,15520.897163,7.032249e+07,1.520496e+05,19123.805685,2.041689,9.504553e+07,9.888558,4545.393731,1.055865,0.353093,21464.027749
min,2.000000,37.000000,0.000000,0.000000,0.000000,1.620000e+02,9.100000e+01,0.000000,0.000000,-2.147484e+09,1927.000000,0.000000,1.600000,1.180000,0.000000
25%,77.000000,96.000000,11.000000,194.500000,745.000000,8.301882e+06,1.966300e+04,1920.500000,0.000000,1.000000e+07,1999.000000,385.000000,5.900000,1.850000,0.000000
50%,139.000000,106.000000,64.000000,436.000000,1000.000000,3.009311e+07,5.397700e+04,4060.000000,1.000000,2.500000e+07,2004.000000,686.000000,6.600000,2.350000,227.000000
75%,224.000000,120.000000,235.000000,691.000000,13000.000000,6.690181e+07,1.286110e+05,16243.000000,2.000000,5.000000e+07,2010.000000,976.000000,7.200000,2.350000,11000.000000
max,813.000000,330.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,2.127520e+09,2016.000000,137000.000000,9.300000,16.000000,349000.000000

In [9]:
df.head(2)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723,178,0,855,Joel David Moore,1000,760505847,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000,2009,936,7.9,1.78,33000
1,Color,Gore Verbinski,302,169,563,1000,Orlando Bloom,40000,309404152,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000,2007,5000,7.1,2.35,0

In [10]:
df['profit']=df['gross']-df['budget']

In [11]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,Color,James Cameron,723,178,0,855,Joel David Moore,1000,760505847,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000,2009,936,7.9,1.78,33000,523505847
1,Color,Gore Verbinski,302,169,563,1000,Orlando Bloom,40000,309404152,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000,2007,5000,7.1,2.35,0,9404152
2,Color,Sam Mendes,602,148,0,161,Rory Kinnear,11000,200074175,Action|Adventure|Thriller,...,English,UK,PG-13,245000000,2015,393,6.8,2.35,85000,-44925825
3,Color,Christopher Nolan,813,164,22000,23000,Christian Bale,27000,448130642,Action|Thriller,...,English,USA,PG-13,250000000,2012,23000,8.5,2.35,164000,198130642
5,Color,Andrew Stanton,462,132,475,530,Samantha Morton,640,73058679,Action|Adventure|Sci-Fi,...,English,USA,PG-13,263700000,2012,632,6.6,2.35,24000,-190641321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5026,Color,Olivier Assayas,81,110,107,45,BÃ©atrice Dalle,576,136007,Drama|Music|Romance,...,French,France,R,4500,2004,133,6.9,2.35,171,131507
5027,Color,Jafar Panahi,64,90,397,0,Nargess Mamizadeh,5,673780,Drama,...,Persian,Iran,Not Rated,10000,2000,0,7.5,1.85,697,663780
5033,Color,Shane Carruth,143,77,291,8,David Sullivan,291,424760,Drama|Sci-Fi|Thriller,...,English,USA,PG-13,7000,2004,45,7.0,1.85,19000,417760
5035,Color,Robert Rodriguez,56,81,0,6,Peter Marquardt,121,2040920,Action|Crime|Drama|Romance|Thriller,...,Spanish,USA,R,7000,1992,20,6.9,1.37,0,2033920
5042,Color,Jon Gunn,43,90,16,16,Brian Herzlinger,86,85222,Documentary,...,English,USA,PG,1100,2004,23,6.6,1.85,456,84122

In [12]:
df.sort_values(by='profit', ascending=False, inplace=True)
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,Color,James Cameron,723,178,0,855,Joel David Moore,1000,760505847,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000,2009,936,7.9,1.78,33000,523505847
29,Color,Colin Trevorrow,644,124,365,1000,Judy Greer,3000,652177271,Action|Adventure|Sci-Fi|Thriller,...,English,USA,PG-13,150000000,2015,2000,7.0,2.00,150000,502177271
26,Color,James Cameron,315,194,0,794,Kate Winslet,29000,658672302,Drama|Romance,...,English,USA,PG-13,200000000,1997,14000,7.7,2.35,26000,458672302
3024,Color,George Lucas,282,125,0,504,Peter Cushing,11000,460935665,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG,11000000,1977,1000,8.7,2.35,33000,449935665
3080,Color,Steven Spielberg,215,120,14000,548,Dee Wallace,861,434949459,Family|Sci-Fi,...,English,USA,PG,10500000,1982,725,7.9,1.85,34000,424449459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2334,Color,Katsuhiro Ã”tomo,105,103,78,101,Robin Atkin Downes,488,410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,...,Japanese,Japan,PG-13,2127519898,2004,336,6.9,1.85,973,-2127109510
2323,Color,Hayao Miyazaki,174,134,6000,745,Jada Pinkett Smith,893,2298191,Adventure|Animation|Fantasy,...,Japanese,Japan,PG-13,-2147483648,1997,851,8.4,1.85,11000,-2145185457
2988,Color,Joon-ho Bong,363,110,584,74,Kang-ho Song,629,2201412,Comedy|Drama|Horror|Sci-Fi,...,Korean,South Korea,R,-2147483648,2006,398,7.0,1.85,7000,-2145282236
3859,Color,Chan-wook Park,202,112,0,38,Yeong-ae Lee,717,211667,Crime|Drama,...,Korean,South Korea,R,-2147483648,2005,126,7.7,2.35,4000,-2147271981
3005,Color,Lajos Koltai,73,134,45,0,PÃ©ter Fancsikai,9,195888,Drama|Romance|War,...,Hungarian,Hungary,R,-2147483648,2005,2,7.1,2.35,607,-2147287760

In [13]:
df.tail(5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
2334,Color,Katsuhiro Ã”tomo,105,103,78,101,Robin Atkin Downes,488,410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,...,Japanese,Japan,PG-13,2127519898,2004,336,6.9,1.85,973,-2127109510
2323,Color,Hayao Miyazaki,174,134,6000,745,Jada Pinkett Smith,893,2298191,Adventure|Animation|Fantasy,...,Japanese,Japan,PG-13,-2147483648,1997,851,8.4,1.85,11000,-2145185457
2988,Color,Joon-ho Bong,363,110,584,74,Kang-ho Song,629,2201412,Comedy|Drama|Horror|Sci-Fi,...,Korean,South Korea,R,-2147483648,2006,398,7.0,1.85,7000,-2145282236
3859,Color,Chan-wook Park,202,112,0,38,Yeong-ae Lee,717,211667,Crime|Drama,...,Korean,South Korea,R,-2147483648,2005,126,7.7,2.35,4000,-2147271981
3005,Color,Lajos Koltai,73,134,45,0,PÃ©ter Fancsikai,9,195888,Drama|Romance|War,...,Hungarian,Hungary,R,-2147483648,2005,2,7.1,2.35,607,-2147287760

In [14]:
df.sort_values(by='profit', ascending=False, inplace=True)
df.head(3)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,Color,James Cameron,723,178,0,855,Joel David Moore,1000,760505847,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000,2009,936,7.9,1.78,33000,523505847
29,Color,Colin Trevorrow,644,124,365,1000,Judy Greer,3000,652177271,Action|Adventure|Sci-Fi|Thriller,...,English,USA,PG-13,150000000,2015,2000,7.0,2.00,150000,502177271
26,Color,James Cameron,315,194,0,794,Kate Winslet,29000,658672302,Drama|Romance,...,English,USA,PG-13,200000000,1997,14000,7.7,2.35,26000,458672302

In [15]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes', 'profit'],
      dtype='object')

In [16]:
df['genres'].unique

<bound method Series.unique of 0                         Action|Adventure|Fantasy|Sci-Fi
29                       Action|Adventure|Sci-Fi|Thriller
26                                          Drama|Romance
3024                      Action|Adventure|Fantasy|Sci-Fi
3080                                        Family|Sci-Fi
                              ...
2334    Action|Adventure|Animation|Family|Sci-Fi|Thriller
2323                          Adventure|Animation|Fantasy
2988                           Comedy|Drama|Horror|Sci-Fi
3859                                          Crime|Drama
3005                                    Drama|Romance|War
Name: genres, Length: 3755, dtype: object>

In [17]:
df['genres']=df['genres'].str.split('|')

In [18]:
df['title_year'] = pd.to_datetime(df['title_year'], format='%Y', errors='coerce')

In [19]:
df.to_excel(r"D:\Ind\projects\Career fair project\imdb_ipynb.xlsx", index=False)